### ISSUE TITLE
Warnings of duplicate dependencies

### ISSUE THREAD

**Issue by ltfschoen** [ChainSafe/Multix#320] opened 2023-08-27 22:59 UTC
**Description**

when i run `yarn start` using Yarn 3.5.1 i get the following warnings in the browser.
i didn't get the warnings previously when i was running it using Yarn 1.

it seems to be because there are version conflicts between what is in the project root yarn.lock, and squid/package-lock.json

```bash
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:buffer:9
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/wasm-crypto requires direct dependencies exactly matching version 7.2.1.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	7.2.2	@polkadot/wasm-bridge
	7.2.2	@polkadot/wasm-crypto-wasm
warn @ versionDetect.js:66
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 12.3.2	node_modules/.vite/deps/
	esm 12.3.2	node_modules/.vite/deps/
warn @ versionDetect.js:66
Show 1 more frame
Show less
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:buffer:9
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 12.3.2	node_modules/.vite/deps/
	esm 12.3.2	node_modules/.vite/deps/
warn @ versionDetect.js:66
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.1	node_modules/.vite/deps/
	esm 7.2.1	node_modules/.vite/deps/
warn @ versionDetect.js:66
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/.vite/deps/
	esm 7.2.1	node_modules/.vite/deps/
warn @ versionDetect.js:66
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.2	node_modules/.vite/deps/
	esm 7.2.1	node_modules/.vite/deps/
warn @ versionDetect.js:66
Show 1 more frame
Show less
versionDetect.js:66 @polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 7.2.1	node_modules/.vite/deps/
	esm 7.2.1	node_modules/.vite/deps/
```

i tried adding the following extra resolutions in the project root package.json, but it still showed the warnings
```bash
  "resolutions": {
    "@polkadot/util": "^12.3.2",
    "@polkadot/util-crypto": "^12.3.2",
    "@polkadot/wasm-bridge": "^7.2.1",
    "@polkadot/wasm-crypto": "^7.2.1",
    "@polkadot/wasm-crypto-wasm": "^7.2.1",
    "@polkadot/wasm-util": "^7.2.1",
    "graphql": "^16.0.0"
  }
```

i also tried running this in the project root and in squid/, but still got the warnings (perhaps that's for Yarn 1 and 2, but not 3)
```bash
npx --yes yarn-deduplicate yarn.lock
```

**Prerequisites**

Add any setup info / environment / account specifics that need to be in place prior to the test

**Steps To Reproduce**

Add clear steps on how to reproduce the bug

1. Run `yarn start`
2. Go to http://localhost:3333/?network=kusama
3. View browser console logs to see warnings

**Expected Behaviour**
Not show duplicate dependency warnings

**Console Error**
As shown above

**Test Host Specifics: **

- OS: Docker Desktop for Mac, macOS 13.4
- Browser Brave
- Version latest

**Comment by Tbaut** [comment] 2023-08-28 11:47
Squid is running npm, because we have to as this is a subsquid requirement. Did you run `yarn start` in the root? In which case I imagine that this is unwanted.

**Comment by ltfschoen** [comment] 2023-08-28 13:03
> 

ahh interesting. actually no, i didn't follow the [instructions](https://github.com/ChainSafe/Multix#running-the-front-end-user-interface-locally) properly that are shown here, as i deviated slightly and called it from within the subdirectory /multix/packages/ui, using this PR https://github.com/ChainSafe/Multix/pull/321/

so i installed the MultixUI dependencies with `yarn install` from the project root here in the Dockerfile https://github.com/ChainSafe/Multix/pull/321/files#diff-608af3cc9f42984f49b1d1eb0c391d69e344734779b0eff2f3909ed9eb0991e3R53

and then i started the MultixUI frontend from the workspace subdirectory /multix/packages/ui with `yarn start --host 0.0.0.0` (but calling into the Docker container) here https://github.com/ChainSafe/Multix/pull/321/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R109, so the code used was `docker exec -w /multix/packages/ui -it multix-ui-dev yarn start --host 0.0.0.0`

so to change it to call it from the project root folder i just changed that code to `docker exec -w /multix -it multix-ui-dev yarn ui:start --host 0.0.0.0`, but when i tried running it with that instead it still showed the same errors in the browser console, so as you say it may be unwanted.

**Comment by Tbaut** [comment] 2023-09-26 21:18
closing as I can't reproduce and it doesn't seem like a blocker.

**Closed by Tbaut** 2023-09-26 21:18 UTC
